HARD : requiredDuringSchedulingIgnoredDuringExecution
SOFT : preferredDuringSchedulingIgnoredDuringExecution
nodeAffinity -- Affinity => In , Exist
nodeAffinity -- Anti-Affinity => NotIn , NotExist
------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      affinity:
        nodeAffinity:  #-----> pod near to each other 🧲
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In # ----------> *
                values:
                - backend
      containers:
      - name: nginx
        image: nginx
--------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:  #-----> pod far away from each other 🚫
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: NotIn  # ----------> *
                values:
                - prod
      containers:
      - name: backend
        image: nginx
        ports:
        - containerPort: 80


