k8s/
├── base/
│   ├── deployment.yaml
│   ├── service.yaml
│   └── kustomization.yaml
└── overlays/
    ├── dev/
    │   ├── kustomization.yaml
    │   └── patch.yaml
    └── prod/
        ├── kustomization.yaml
        └── patch.yaml
---------------------------------------------------------------------> BASE
--------------------base/deployment.yaml------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
-----------------base/service.yaml-----------------------------
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
-----------------base/kustomization.yaml----------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
#optional part for add lable to all resources
commonLabels:
  company: test-lable
---------------------------------------------------------------------> DEV
------------------overlays/dev/patch.yaml---------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1 #---> with patch we can ignor (replicas: 1) here its equal
-----------------overlays/dev/kustomization.yaml--------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base #---> load resource from <base> folder

patches:
  - patch.yaml
#---OR--->
patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
---------------------------------------------------------------------> PROD
-----------------overlays/prod/patch.yaml--------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3 #---> with patch we can ignor (replicas: 1) and implelment (replicas: 3)
-----------------overlays/prod/kustomization.yaml------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  #---> load resource from <base> folder

patches:
  - patch.yaml
-----------------------Run(with -k parameter)---------------------------> RUN
kubectl apply -k k8s/overlays/dev
kubectl apply -k k8s/overlays/prod

------------------------------------other folder structure---------------------------------------------->
k8s/
├── base/
│   ├── kustomization.yaml
│   ├── nginx-depl.yaml
│   ├── service.yaml
│   └── redis-depl.yaml
└── overlays/
    ├── dev/
    │   ├── kustomization.yaml
    │   ├── config-map.yaml #---> we can have another resource here too
    │   └── volume.yaml
    ├── stg/
    │   ├── kustomization.yaml
    │   └── config-map.yaml
    └── prod/
        ├── kustomization.yaml
        ├── config-map.yaml
        └── grafana-depl.yaml
-----------------------------------------------
# we can have multi folder and sub folder too
k8s/
├── base/
│   ├── kustomization.yaml
│   ├── db/
│   │   ├── db-depl.yaml
│   │   ├── db-service.yaml
│   │   └── kustomization.yaml
│   └── api/
│       ├── api-depl.yaml
│       ├── api-service.yaml
│       └── kustomization.yaml
└── overlays/
    ├── dev/
    │   ├── kustomization.yaml
    │   ├── db/
    │   │   ├── db-patch.yaml
    │   │   └── kustomization.yaml
    │   └── api/
    │       ├── api-patch.yaml
    │       └── kustomization.yaml
    └── prod/
        ├── kustomization.yaml
        ├── db/
        │   ├── db-patch.yaml
        │   └── kustomization.yaml
        └── api/
            ├── api-patch.yaml
            └── kustomization.yaml













