List
  0,1,2,3,... = index
  - = Add
-------------------------------------------- List------------------------------------------------->
# api-depl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: nginx #---> we want to change
          image: nginx #--->  we want to change
-------------------------------------Change in List------------------------------------------------->
--------------inline------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-depl.yaml

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0 #---> for the list we use number from 0,1,2,...
        value:
          name: haproxy #---> name: nginx => name: haproxy
          image: haproxy #---> image: nginx => name: haproxy
--------------merge------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - label-patch.yaml
---
# label-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx #---> old name(image: nginx)****
          image: haproxy #---> new name(image: haproxy)
--------------------------------------------Add in List--------------------------------------------------------->
--------------inline------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-depl.yaml

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/-  #---> (-) mean add in array
        value:
          name: haproxy
          image: haproxy
-------result-----
...
containers:
  - name: nginx
    image: nginx
  - name: haproxy
    image: haproxy
...
--------------merge------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - label-patch.yaml
----label-patch.yaml---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  template:
    spec:
      containers:
        - name: haproxy
          image: haproxy
-------result-----
...
containers:
  - name: nginx
    image: nginx
  - name: haproxy
    image: haproxy
...
--------------------------------------------Delete in List--------------------------------------------------------->
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: nginx
          image: nginx
        - name: web
          image: web
--------------inline------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-depl.yaml

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/1 #---> remove the second index
--------------merge------------------------->
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - label-patch.yaml
--------label-patch.yaml----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  template:
    spec:
      containers:
        - name: database
          $patch: delete #---> we put $ here for do delete(exception)
------------------------------------------------------------------------------------------------------------




















