apiVersion: v1
kind: Service
metadata:
  name: external-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-postgres
subsets:
  - addresses:
      - ip: 172.38.100.68
    ports:
      - port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
type: Opaque
stringData:
  PGUSER: user1
  PGPASSWORD: mypass
  PGDATABASE: myDbName
---
apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: pg-client
      image: postgres:15
      command: ["sleep", "3600"]
      env:
        - name: DB_HOST
          value: "external-postgres.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
      envFrom:
        - secretRef:
            name: pg-credentials
----------------------------------------------------------
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME"






