{
  "person": {
    "name": "Ali",
    "age": 30,
    "skills": ["docker", "kubernetes", "aws"]
  }
}
--------------------------------
$                 ریشه
*                 ALL
$.person           ورود به person
$.person.name      فیلد name
[*]               همه اعضای لیست
[0]               عضو اول لیست
[start:end]       [1:2]
$..age  recrsive(all filed that named "age" in the file)

--------------------------------
$.person.name  => Ali
$.person.age  => 30
$.person.skills[*]  => docker kubernetes aws
$.person.skills[0]  => docker
$.person.skills[1:2] => docker kubernetes
$.person['name','age'] => ali 30
