---------------------install--------------------

pip3 install jsonpath-ng
--------------------use case---------------------
#jpath '$.property1'
kubectl get pods -o jsonpath='{.items[*].metadata.name}'
aws ec2 describe-instances --query 'Reservations[].Instances[].InstanceId'
-----------------------------------------
{
  "person": {
    "name": "Ali",
    "age": 30,
    "skills": ["docker", "kubernetes", "aws"]
  }
}
--------------------------------
$                 ریشه
*                 ALL
$.person           ورود به person
$.person.name      فیلد name
[*]               همه اعضای لیست
[0]               عضو اول لیست
[start:end]       [1:2]
$..age  recrsive(all filed that named "age" in the file)
[?()]  condition--> see condition file
--------------------------------
$.person.name  => Ali
$.person.age  => 30
$.person.skills[*]  => docker kubernetes aws
$.person.skills[0]  => docker
$.person.skills[1:2] => docker kubernetes
$.person['name','age'] => ali 30
-----------------------------another form---------------------------------->
[
  "car", 
  "bus", 
  "truck", 
  "bike"
]
-----------------
$[0]  => [car]
$[3] => [bike]
$[0,1]  => [car , bus]

