openssl genrsa -out user.key 2048
openssl req -new -key user.key -out user.csr \
  -subj "/CN=win-user/O=win-group"
openssl x509 -req -in user.csr \
  -CA /etc/kubernetes/pki/ca.crt \
  -CAkey /etc/kubernetes/pki/ca.key \
  -CAcreateserial \
  -out user.crt \
  -days 365
-------------------------------------limitation put on our config file(user)-------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ali-read-pods
  namespace: dev
subjects:
- kind: User
  name: win-user          #------> user the user for put limitation on it
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
