openssl genrsa -out user.key 2048
openssl req -new -key user.key -out user.csr \
  -subj "/CN=win-user/O=win-group"
openssl x509 -req -in user.csr \
  -CA /etc/kubernetes/pki/ca.crt \
  -CAkey /etc/kubernetes/pki/ca.key \
  -CAcreateserial \
  -out user.crt \
  -days 365
-------------------------------------limitation put on our config file(user)-------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ali-read-pods
  namespace: dev
subjects:
- kind: User
  name: win-user          #------> user the user for put limitation on it
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---------------------------------------create managed certificate------------------------------------------------
openssl genrsa -out jane.key 2048
openssl req -new -key jane.key -out jane.csr \
  -subj "/CN=jane"
cat jane.csr | base64 | tr -d '\n'
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  request: <BASE64_CSR> #------------> cat jane.csr | base64 | tr -d '\n'
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
---
kubectl apply -f jane-csr.yaml
kubectl get csr
kubectl certificate approve jane
kubectl certificate deny jane #----> if we did not accepted it
kubectl delete csr jane   #-----> or delete it
kubectl get csr jane -o jsonpath='{.status.certificate}' \
  | base64 -d > jane.crt
