https://github.com/kubernetes/sample-controller
A CRD only defines a new resource type in Kubernetes; to make it do anything, you need a *controller (operator) — tools like *ArgoCD and *Knative *AWS are real-world examples built on CRDs plus controllers.
All operator: https://operatorhub.io/
-------------------------------------------------
kubectl get crd
kubectl describe crd <name>
------------------------------------------------------
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flights.com
spec:
  group: flights.com
  scope: Namespaced
  names:
    kind: FlightTicket
    singular: flightticket
    plural: flighttickets
    shortNames:
      - ft
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                number:
                  type: integer
                  minimum: 1
                  maximum: 10
---------------------------------------------------
apiVersion: flights.com/v1
kind: FlightTicket
metadata:
  name: my-flight-ticket
spec:
  from: Mumbai
  to: London
  number: 2
