Not supported for Flannel or AWS EKS
-----------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: db-pod 
  labels:
    app: db
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
  - name: api
    image: nginx
-------------------------------------Ingress------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-db
spec:
  podSelector:
    matchLabels:
      app: db          #---> Apply for pod with app=db -- main pod 
  policyTypes:
  - Ingress
  ingress:  #----> ingress traffic
  - from:
    - podSelector:
        matchLabels:
          app: api      #---> accept traffic from pod with app=api 
    ports:
    - protocol: TCP
      port: 3306
--------------------------------Egress-----------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-egress-to-db
spec:
  podSelector:
    matchLabels:
      app: api      #---> Apply for pod with app=api -- main pod
  policyTypes:
  - Egress
  egress:  #----> egress traffic
  - to:
    - podSelector:
        matchLabels:
          app: db   #---> send traffic to pod with app=db 
      #----- optinal - limit on namespace----> kubectl label namespace default kubernetes.io/metadata.name=deafult
      namespaceSelector: #--->  if we want limit to special namespace
        matchLabels:
          kubernetes.io/metadata.name: default #---> we can see all lable ==> kubectl get ns default --show-labels
      #----- optional - accept from ip-----------
      ipBlock:
        cidr: 10.0.12.34/32
        
      #------- OR---------------
      # - namespaceSelector: ...
      # - ipBlock: ...
      #------- AND---------------
      # - namespaceSelector: ...
      #   ipBlock: ...
      
    ports:
    - protocol: TCP
      port: 3306  
----------------------------------------------Both-----------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      role: db

  policyTypes:
  - Ingress
  - Egress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: api-pod
    ports:
    - protocol: TCP
      port: 3306

  egress:
  - to:
    - ipBlock:
        cidr: 192.168.5.10/32
    ports:
    - protocol: TCP
      port: 80

