apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
---------------------------rolebinding to user------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding
  namespace: dev
subjects:
- kind: User  #--------> link to user
  name: dev-user
roleRef:
  kind: Role
  name: developer #-----> role name
  apiGroup: rbac.authorization.k8s.io
---------------------------rolebinding to ServiceAccount------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-binding
  namespace: dev
subjects:
- kind: ServiceAccount #--------> link to serviceaccount
  name: my-sa
  namespace: dev
roleRef:
  kind: Role
  name: developer #-----> role name
  apiGroup: rbac.authorization.k8s.io

