------------------------------------------for test senario and temporary and its not for real use beacuse we shoud update our Token every 1 hour --------------------------------------------------
kubectl create namespace dev
kubectl create serviceaccount gitlab-sa -n dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-role
  namespace: dev
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: gitlab-sa
  namespace: dev
roleRef:
  kind: Role
  name: deploy-role
  apiGroup: rbac.authorization.k8s.io
---------------create Token and Envirement variable -------------------------------
kubectl create token gitlab-sa -n dev --duration=1h
-------------- GitLab variables----
K8S_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
K8S_API=https://<API_SERVER>:6443
--------------------.gitlab-ci.yml-------------------------------------------------
stages:
  - deploy

image: bitnami/kubectl:latest

deploy:
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$K8S_API" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab --token="$K8S_TOKEN"
    - kubectl config set-context ctx --cluster=k8s --user=gitlab --namespace=dev
    - kubectl config use-context ctx
    - kubectl apply -f deployment.yaml
-------------------------------------------------*for real senario and not temporary we shoud install gitlab-runner on our kubernete cluster----------------------------------------
kubectl create namespace gitlab-runner

kubectl -n gitlab-runner create serviceaccount gitlab-runner

kubectl apply -f - <<'YAML'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","pods/exec","pods/log","secrets","configmaps","services","events","namespaces"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets","statefulsets"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get","list","watch"]
YAML

kubectl apply -f - <<'YAML'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-crb
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab-runner
roleRef:
  kind: ClusterRole
  name: gitlab-runner-clusterrole
  apiGroup: rbac.authorization.k8s.io
YAML
--------------------values.yaml----------
gitlabUrl: "https://gitlab.com/"
runnerRegistrationToken: "PASTE_YOUR_TOKEN"

rbac:
  create: false

serviceAccount:
  create: false
  name: gitlab-runner

runners:
  name: "k8s-runner"
  tags: "k8s"
  locked: false
  runUntagged: true
  executor: "kubernetes"

  config: |
    [[runners]]
      name = "k8s-runner"
      url = "https://gitlab.com/"
      token = "PASTE_YOUR_TOKEN"
      executor = "kubernetes"

      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine:3.19"
        privileged = false
        service_account = "gitlab-runner"
        poll_timeout = 600
--------------------
helm repo add gitlab https://charts.gitlab.io
helm repo update

helm install gitlab-runner gitlab/gitlab-runner \
  -n gitlab-runner \
  -f values.yaml
  
kubectl -n gitlab-runner get pods




