ServiceAccount => Just for machine
-----------------------------
kubectl get serviceaccount
kubectl get sa
kubectl create serviceaccount my-sa
kubectl delete serviceaccount my-sa
kubectl create sa my-sa -n my-namespace --dry-run=client -o yaml > sa.yaml
--------- automaticly mount token in pod in path => /var/run/secrets/kubernetes.io/serviceaccount/token ----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
  #---- if we don't want mount token for security issue in pod in path => /var/run/secrets/kubernetes.io/serviceaccount/token 
  #spec:
  #  automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: app-sa #--------> connect pod to ServiceAccount
  containers:
  - name: app
    image: nginx
--------------------Add Role&RoleBinding for ServiceAccount -----------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: app-sa  #-----------------> link with ServiceAccount
  namespace: default
roleRef:
  kind: Role
  name: pod-reader #-----------------> link with Role
  apiGroup: rbac.authorization.k8s.io
