-------------------------------emptyDir------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo Hello > /data/file.txt && sleep 3600"]
    volumeMounts:
    - name: my-volume
      mountPath: /data

  volumes:
  - name: my-volume
    emptyDir: {}
--------------------------------hostPath-----------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /host && sleep 3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /host

  volumes:
  - name: host-volume
    hostPath:
      path: /var/log
      type: Directory
--------------------------------ConfigMap-----------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.conf: |
    ENV=production
    LOG_LEVEL=info
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /config/app.conf && sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /config

  volumes:
  - name: config-volume
    configMap:
      name: app-config
---------------------------------Secret----------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=   # password
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /secret/password && sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /secret
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
-------------------------------NFS------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: nfs-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /nfs && sleep 3600"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /nfs

  volumes:
  - name: nfs-volume
    nfs:
      server: 10.0.0.10
      path: /exports
--------------------------------PersistentVolume-----------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo DATA > /data/file.txt && sleep 3600"]
    volumeMounts:
    - name: pvc-volume
      mountPath: /data

  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: pvc-demo
-------------------------------------------------------------------

























