-----------------------------Server NFS(192.168.174.128)--------------------------------
mkdir /exports
cd /exports/
mkdir backup
apt install nfs-kernel-server
systemctl status nfs-kernel-server.service
nano /etc/exports
  /exports/backup 192.168.174.0/255.255.255.0(rw,sync,no_root_squash)
systemctl restart nfs-kernel-server
systemctl status nfs-kernel-server
-------------------------------Client(kubernetes control plane & nodes)-----------------------------------
apt install nfs-common -y
--------------------------------use it--------------------------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.174.128 #---> server ip
    path: /exports/backup
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app-using-nfs
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /data && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: shared-volume

  volumes:
  - name: shared-volume
    persistentVolumeClaim: #----> we can now use it in our pod
      claimName: nfs-pvc

