kubectl set image deployment/deployment_name container_name=nginx:1.20
kubectl rollout history deployment myapp
kubectl rollout undo deployment myapp
kubectl rollout undo deployment myapp --to-revision=2
kubectl rollout status deployment myapp
------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # Or => Recreate
    rollingUpdate:
      maxSurge: 1 # ---------------
      maxUnavailable: 0 # ---------------
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:1.19
