kubectl create secret generic my-secret \
  --from-literal=username=admin \
  --from-literal=password=12345
-----------------From file------------------------
kubectl create secret generic my-secret \
  --from-file=ssh-privatekey=./id_rsa \
  --from-file=ssh-publickey=./id_rsa.pub
-----------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=        # echo -n "admin" | base64
  password: MTIzNDU=        # echo -n "12345" | base64
