1.Stable Network Identity
mydb-0
mydb-1
mydb-2
dns => mydb-0.mydb-headless.default.svc.cluster.local
2.Stable Storage
data-mydb-0
data-mydb-1
data-mydb-2
3.Ordered Operations
pod1 => pod2 => pod3
----------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis" # must be headless service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  clusterIP: None   #  headless
  selector:
    app: redis
